// Open Siege spec 16/01 — dts-viewer's host-side wiring for libcscript_core.

#include "cscript_host.hpp"
#include "player_simobject.hpp"
#include "entity_bindings.hpp"
#include "hud_bindings.hpp"

#include "console/console.h"
#include "console/script.h"
#include "console/runtime.h"
#include "console/sim.h"
#include "console/arrayObject.h"
#include "console/scriptObjects.h"
#include "console/torquescript/runtime.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>

namespace {

// Force the linker to pull in TUs whose only externally-visible symbols
// are static class registrations (IMPLEMENT_CONOBJECT side-effects). On
// macOS / Mach-O, a static archive only contributes TUs that resolve
// otherwise-unresolved symbols — so without these touchpoints, scripts
// asking to `new ScriptObject` etc. fail with "non-conobject class".
//
// Implementation: call getStaticClassRep (generated by IMPLEMENT_CONOBJECT)
// from a function that's actually invoked at startup. A static-variable
// anchor with `volatile` is silently elided by the optimizer; only a
// runtime use is reliably preserved.
[[gnu::noinline]] void anchorScriptableClasses()
{
    static AbstractClassRep* anchors[] = {
        ScriptObject::getStaticClassRep(),
        ArrayObject::getStaticClassRep(),
    };
    // Sink the result so the calls aren't dropped.
    if (anchors[0] == nullptr || anchors[1] == nullptr)
        std::fprintf(stderr, "[cscript] anchor unexpectedly null\n");
    // Spec 16/05 — Player SimObject class. Lives in dts_viewer:: so the
    // anchor function is in the same TU as IMPLEMENT_CONOBJECT(Player).
    dts_viewer::anchorPlayerClass();
    // Spec 16/06 — Item / Turret / StaticShape / Moveable / Generator /
    // Trigger / VehiclePlaceholder / Door / MissionMarker / SimLight /
    // Sky / Planet / Sensor — 13 entity SimObject subclasses.
    dts_viewer::anchorEntityClasses();
    // Spec 17/03 — addObjective / setObjectiveState / removeObjective /
    // notify / centerPrint / bottomPrint / setMissionState free
    // functions. The anchor only matters if hud_bindings.cpp gets
    // archive-bundled in the future; today it's a direct TU.
    dts_viewer::anchorHudBindings();
}

} // namespace

namespace {

bool g_initialised = false;
bool g_verbose     = false;
int  g_suppressed  = 0;

// Spec 17/06 — Tribes corpus regularly trips two modern-Torque
// compile warnings on legitimate idioms. Filter them at the consumer
// so the user-facing log is readable. `--verbose-cscript` bypasses.
bool is_benign_tribes_warning(const char* line)
{
    if (!line) return false;
    // Compile-warning prefix is "Script Warning: Variable %X referenced
    // before used" — match the substring after the level prefix.
    if (std::strstr(line, "referenced before used") != nullptr) return true;
    if (std::strstr(line, "string always evaluates to 0") != nullptr) return true;
    return false;
}

void consoleSink(unsigned int /*level*/, const char* line)
{
    if (!g_verbose && is_benign_tribes_warning(line)) {
        ++g_suppressed;
        return;
    }
    std::printf("[cscript] %s\n", line);
}

} // namespace

namespace dts_viewer::cscript {

void init()
{
    if (g_initialised)
        return;
    anchorScriptableClasses();
    Con::init();
    Sim::init();
    Con::addConsumer(&consoleSink);
    // TorqueScriptRuntime's constructor auto-registers itself with
    // Con::registerRuntime(0, this). Skip an explicit re-registration —
    // the second call would trip an AssertFatal in debug builds because
    // gRuntimes[0] is already set.
    (void)studio::content::cscript::TorqueScript::getRuntime();

    g_initialised = true;
    std::printf("[cscript] host initialised — VM ready\n");
}

bool runFile(const std::string& path)
{
    init();
    std::ifstream f(path, std::ios::binary);
    if (!f)
        return false;
    std::ostringstream buf;
    buf << f.rdbuf();
    Con::evaluate(buf.str().c_str(), false, path.c_str());
    return true;
}

void eval(const std::string& src)
{
    init();
    Con::evaluate(src.c_str(), false, "inline");
}

void set_verbose(bool verbose) { g_verbose = verbose; }

int flush_suppression_count()
{
    const int n = g_suppressed;
    g_suppressed = 0;
    return n;
}

} // namespace dts_viewer::cscript
