// Open Siege spec 16/01 — dts-viewer's host-side wiring for libcscript_core.

#include "cscript_host.hpp"
#include "player_simobject.hpp"
#include "entity_bindings.hpp"

#include "console/console.h"
#include "console/script.h"
#include "console/runtime.h"
#include "console/sim.h"
#include "console/arrayObject.h"
#include "console/scriptObjects.h"
#include "console/torquescript/runtime.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>

namespace {

// Force the linker to pull in TUs whose only externally-visible symbols
// are static class registrations (IMPLEMENT_CONOBJECT side-effects). On
// macOS / Mach-O, a static archive only contributes TUs that resolve
// otherwise-unresolved symbols — so without these touchpoints, scripts
// asking to `new ScriptObject` etc. fail with "non-conobject class".
//
// Implementation: call getStaticClassRep (generated by IMPLEMENT_CONOBJECT)
// from a function that's actually invoked at startup. A static-variable
// anchor with `volatile` is silently elided by the optimizer; only a
// runtime use is reliably preserved.
[[gnu::noinline]] void anchorScriptableClasses()
{
    static AbstractClassRep* anchors[] = {
        ScriptObject::getStaticClassRep(),
        ArrayObject::getStaticClassRep(),
    };
    // Sink the result so the calls aren't dropped.
    if (anchors[0] == nullptr || anchors[1] == nullptr)
        std::fprintf(stderr, "[cscript] anchor unexpectedly null\n");
    // Spec 16/05 — Player SimObject class. Lives in dts_viewer:: so the
    // anchor function is in the same TU as IMPLEMENT_CONOBJECT(Player).
    dts_viewer::anchorPlayerClass();
    // Spec 16/06 — Item / Turret / StaticShape / Moveable / Generator /
    // Trigger / VehiclePlaceholder / Door / MissionMarker / SimLight /
    // Sky / Planet / Sensor — 13 entity SimObject subclasses.
    dts_viewer::anchorEntityClasses();
}

} // namespace

namespace {

bool g_initialised = false;

void consoleSink(unsigned int /*level*/, const char* line)
{
    std::printf("[cscript] %s\n", line);
}

} // namespace

namespace dts_viewer::cscript {

void init()
{
    if (g_initialised)
        return;
    anchorScriptableClasses();
    Con::init();
    Sim::init();
    Con::addConsumer(&consoleSink);
    // TorqueScriptRuntime's constructor auto-registers itself with
    // Con::registerRuntime(0, this). Skip an explicit re-registration —
    // the second call would trip an AssertFatal in debug builds because
    // gRuntimes[0] is already set.
    (void)studio::content::cscript::TorqueScript::getRuntime();

    // Tribes corpus has plenty of warnings (use-before-set, etc.) that
    // the modern Torque compiler treats as Fatal-ISV asserts. The
    // T1-shipped scripts predate that strictness — flip the flag so
    // mission gameplay-rules scripts log warnings instead of aborting.
    Con::evaluate("$Con::scriptWarningsAsAsserts = false;",
                  false, "cscript_host.init");

    g_initialised = true;
    std::printf("[cscript] host initialised — VM ready\n");
}

bool runFile(const std::string& path)
{
    init();
    std::ifstream f(path, std::ios::binary);
    if (!f)
        return false;
    std::ostringstream buf;
    buf << f.rdbuf();
    Con::evaluate(buf.str().c_str(), false, path.c_str());
    return true;
}

void eval(const std::string& src)
{
    init();
    Con::evaluate(src.c_str(), false, "inline");
}

} // namespace dts_viewer::cscript
